name: go-test
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "FIRST JOB"
      - run: echo "SECOND JOB"
      - run: echo "THIRD JOB"
      - name: Check out repository name
        uses: actions/checkout@v2
      
